spring.application.name=hackathon-be
spring.profiles.default=local

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jackson.time-zone=UTC

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000}
